#!/bin/bash


if [ $# = 0 ]; then
      
      echo "
Welcome to FreePort :) 
Get Rid of Address/Port already in use error with a single command.
(For Local Development Purposes Only)

👉  $(tput setaf 5)$(tput smso) https://github.com/thenullterminator/FreePort $(tput sgr0) 

Usage: freeport [PORT_NUMBER]
"
      exit 1
fi


cd $HOME/.freeport
./main.sh $1
cd $OLDPWD
