#!/bin/bash

# Working from current directory having freeport

TARGET_DIR="$HOME/.freeport"


# verify if this is current directory
if [[ -f "main.sh" && -f "README.md" && -f "freeport" ]]; then
    :
else
    echo "please cd to the folder containing proxyman"
    exit 1
fi

# copy the contents to ~/.freeport/ (hidden folder in home directory)
mkdir -p $TARGET_DIR
cp * $TARGET_DIR

# add to path
mkdir -p $HOME/.local/bin
cp freeport $HOME/.local/bin
chmod +x $HOME/.local/bin/freeport

# which proxyman &> /dev/null
# if [ "$?" != 0 ]; then
#     echo "Failed to install :("
#     exit
# fi

echo "Installed successfully."
